### ISSUE TITLE
About Running Environment

### ISSUE THREAD

**Issue by junkunyuan** [YanzuoLu/MALE#1]
Hi, I am trying to run your code. But I encountered some error.

Could you please provide details about your running environment in README? 
For example, the version of timm, pytorch, torchvision.

Thanks very much!

**Comment by YanzuoLu** [comment]
Thank you for your attention to our work, I will complete it today.

**Comment by YanzuoLu** [comment]
@junkunyuan Hi, I have completed the relevant installation tutorial and checkpoints download link in README, and added example scripts to run the pre-training and fine-tuning, hopefully this can help you. If you encounter evaluation-related problems during fine-tuning, you can find a version written in cython in [fast-reid](https://github.com/JDAI-CV/fast-reid/tree/master/fastreid/evaluation/rank_cylib) to improve. Sorry for the late reply, because I set the wrong notification email address before, thank you again for your attention to our work.

**Comment by YanzuoLu** [comment]
If you have any other questions, feel free to let me know here, thanks.

**Comment by junkunyuan** [comment]
Thank you very much!
